version: '3'
services:
  task-api:
    #env_file:
     # - dev-variables.env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "7000:7000"
    volumes:
      - .:/app      